#!/usr/bin/env sh
# This is built for arch linux distros with yay preinstalled
yay -Syy
yay --noconfirm
yay -S fish --needed
chsh -s /usr/bin/fish
cd $HOME/.config/yadm
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher update
fish bootstrap.fish
