#!/usr/bin/env sh
cd $HOME
git clone https://github.com/kleutzinger/scripts.git

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

ln -s ~/.vimrc ~/.config/nvim/init.vim
