#!/usr/bin/env sh

# https://github.com/RaitaroH/sxhkd_plasma
super + alt + {Right,Left}
    {qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Window to Next Desktop',\
    qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Window to Previous Desktop'}

# https://web.archive.org/web/20200816032902/https://my-take-on.tech/2020/07/03/some-tricks-for-sxhkd-and-bspwm/#reloading-sxhkdrc

super + shift + r
    pkill -usr1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'

super + k
    /home/kevin/scripts/edit-hotkeys.sh

super + w
    firefox

super + Return
    mini-kitty.sh

super + space
    dmenu_run -fn "-xos4-terminus-medium-r-*-*-14-*"

super + q
    wmctrl -c :ACTIVE:

Print
    flameshot gui

F1
    /home/kevin/scripts/toggle-term.sh

super + n
    terminator --title newsboat -e "newsboat"

super + e
    nautilus

super + b
    $BROWSER 127.0.0.1:9001/admin/

super + o
    terminator -m -e "game.sh"
