#!/usr/bin/env sh

# https://github.com/RaitaroH/sxhkd_plasma
super + alt + {Right,Left}
    {qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Window to Next Desktop',\
    qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Window to Previous Desktop'}

# https://web.archive.org/web/20200816032902/https://my-take-on.tech/2020/07/03/some-tricks-for-sxhkd-and-bspwm/#reloading-sxhkdrc

super + shift + r
    pkill -usr1 -x sxhkd; notify-send -t 15000 'sxhkd' 'Reloaded config'

super + k
    /home/kevin/scripts/edit-hotkeys.sh

super + w
    firefox

super + Return
    mini-kitty.sh

super + space
    dmenu_run -fn "-xos4-terminus-medium-r-*-*-14-*"

super + q
    wmctrl -c :ACTIVE:

Print
    flameshot gui

shift + Print
    flameshot full -p /home/kevin/Pictures/scrots

F1
    /home/kevin/scripts/toggle-term.sh

shift + F1
    tdrop firefox

super + n
    terminator --title newsboat -e "newsboat"

super + e
    nautilus

super + b
    $BROWSER 127.0.0.1:9001/admin/

super + o
    terminator -m -e "game.sh"

super + shift + o
    cool-retro-term -e game.sh d

super + c
    qdbus org.kde.KWin /Compositor suspend; notify-send "suspend compositor"

super + shift + c
    qdbus org.kde.KWin /Compositor resume; notify-send "resume compositor"

# Disconnect from PS4 controller
super + shift + b
    bluetoothctl -- disconnect 1C:66:6D:C4:DD:FA && notify-send -t 1000 "Disconnected from Dualshock 4"

# Put computer to sleep
super + shift + s
    systemctl suspend

super + shift + f
    ~/scripts/clip-fmt-py.sh && notify-send -t 1000 "Fmt Python"
