#!/usr/bin/env python
"""
from: https://github.com/astral-sh/uv/issues/12193#issuecomment-2752712973
"""
import os, sys
script = os.path.realpath(sys.argv[1])
scriptDir = os.path.dirname(script)
os.execlp('uv', 'uv', 'run', '--project', scriptDir, script, *sys.argv[2:])
